<a href="https://colab.research.google.com/github/dubutoka/Pytorch-Tutorial/blob/main/Intro_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np

In [3]:
# Lists

my_list = [[1,2,3,4,5],[6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [4]:
np1 = np.random.rand(3,4)
np1

array([[0.10029842, 0.53486418, 0.89014291, 0.62662486],
       [0.10079233, 0.96106533, 0.598643  , 0.39751936],
       [0.64256246, 0.49858175, 0.9238772 , 0.75436931]])

In [5]:
np1.dtype

dtype('float64')

In [6]:
# Tensors

tensor_2d = torch.randn(3,4)
tensor_2d
tensor_2d.dtype

torch.float32

In [7]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
# create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.1003, 0.5349, 0.8901, 0.6266],
        [0.1008, 0.9611, 0.5986, 0.3975],
        [0.6426, 0.4986, 0.9239, 0.7544]], dtype=torch.float64)

In [9]:
# tensor operations

my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# reshape and view
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [11]:
# reshape if we dont know number of items using -1

my_torch2 = torch.arange(15)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
my_torch2 = my_torch2.reshape(-1,5)
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [13]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [15]:
# reshape and view are very similar, with reshape and view they will update

In [16]:
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [18]:
my_torch5[1] = 4141
my_torch5

# changing items in tensor with reshape leads to updated tensor

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [19]:
my_torch6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [20]:
# Slices
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# grab a specific item
my_torch7[7]

tensor(7)

In [23]:
# grab slice
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [25]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [26]:
# return column
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])